name: Package

on:
  push:
    branches:
      - production

jobs:
  package:
    name: Package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Install
        run: docker-compose run --user root -T npm install
      - name: Build
        run: docker-compose run --user root -T npm run build
      - name: Publish
        run: 'docker-compose run --user root -T npm publish --access public || true'
