name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: docker-compose run --user root -T npm install
      - name: Build
        run: docker-compose run --user root -T npm build
      - name: Pack
        run: docker-compose run --user root -T npm pack
      - name: Prepare
        run: mv *.tgz package.tgz
      - name: Tests
        run: docker-compose run --user root -T npx package.tgz README.md
